// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znejyrfbyzcqvdpfhmmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZWp5cmZieXpjcXZkcGZobW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDYyOTYsImV4cCI6MjA2MjI4MjI5Nn0.9fNa_ernDTBatbt6DmlFjMFIVp9ylI8ULhK-Ujvo2Ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);